# https://golangci-lint.run/usage/linters/
linters:
  enable-all: true
  disable:
    - contextcheck
    - exhaustivestruct
    - golint
    - interfacer
    - lll
    - maligned
    - scopelint

linters-settings:
  varnamelen:
    ignore-decls:
      - l *rec.Logger
      - w http.ResponseWriter

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - dupl
        - exhaustivestruct
        - funlen
        - goconst
        - goerr113
        - gomnd
